// Supabase Edge Function: weekly-progress-report
// Schedule: 0 5 * * 1  (every Monday at 5 AM UTC)
// Computes weekly stats for every active senior. AI summary is generated by the
// Next.js API /api/reports/weekly when fetched, to keep AI calls in one place.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

Deno.serve(async (req) => {
  const authHeader = req.headers.get("authorization") ?? "";
  const expected = `Bearer ${Deno.env.get("CRON_SECRET") ?? ""}`;
  if (authHeader !== expected) return new Response("Unauthorized", { status: 401 });

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );

  const now = new Date();
  const weekEnd = new Date(now);
  weekEnd.setUTCDate(now.getUTCDate() - now.getUTCDay() - 1);
  weekEnd.setUTCHours(23, 59, 59, 999);
  const weekStart = new Date(weekEnd);
  weekStart.setUTCDate(weekEnd.getUTCDate() - 6);
  weekStart.setUTCHours(0, 0, 0, 0);

  const wkStartStr = weekStart.toISOString();
  const wkEndStr = weekEnd.toISOString();

  const { data: seniors } = await supabase.from("seniors").select("id");
  if (!seniors) return new Response("No seniors", { status: 200 });

  let count = 0;
  for (const s of seniors) {
    const [{ data: medLogs }, { data: bp }, { data: sugar }, { data: missed }, { data: lonely }, { data: checkins }] = await Promise.all([
      supabase.from("medication_logs").select("status").eq("senior_id", s.id).gte("scheduled_time", wkStartStr).lte("scheduled_time", wkEndStr),
      supabase.from("blood_pressure_records").select("id").eq("senior_id", s.id).gte("recorded_at", wkStartStr).lte("recorded_at", wkEndStr),
      supabase.from("blood_sugar_records").select("id").eq("senior_id", s.id).gte("recorded_at", wkStartStr).lte("recorded_at", wkEndStr),
      supabase.from("missed_reminder_alerts").select("id").eq("senior_id", s.id).gte("created_at", wkStartStr).lte("created_at", wkEndStr),
      supabase.from("wellness_checkins").select("id").eq("senior_id", s.id).eq("mood", "lonely").gte("checked_in_at", wkStartStr).lte("checked_in_at", wkEndStr),
      supabase.from("wellness_checkins").select("id").eq("senior_id", s.id).gte("checked_in_at", wkStartStr).lte("checked_in_at", wkEndStr),
    ]);

    const total = (medLogs ?? []).length;
    const taken = (medLogs ?? []).filter((l: { status: string }) => l.status === "taken").length;
    const compliance = total > 0 ? Math.round((taken / total) * 100) : 100;

    await supabase.from("weekly_progress_reports").upsert({
      senior_id: s.id,
      week_start: weekStart.toISOString().slice(0, 10),
      week_end: weekEnd.toISOString().slice(0, 10),
      med_compliance_pct: compliance,
      missed_reminders_count: (missed ?? []).length,
      loneliness_logs_count: (lonely ?? []).length,
      bp_logs_count: (bp ?? []).length,
      sugar_logs_count: (sugar ?? []).length,
      wellness_checkins_count: (checkins ?? []).length,
    }, { onConflict: "senior_id,week_start" });

    count++;
  }

  return new Response(JSON.stringify({ processed: count }), { headers: { "Content-Type": "application/json" } });
});
